FROM debian:jessie

RUN apt-get update -y

RUN apt-get install -y make pkg-config git
RUN apt-get install -y gcc-arm-none-eabi
RUN apt-get install -y gdb-arm-none-eabi
# RUN echo 'arm-none-eabi-gdb -ex "target remote localhost:1234" /Users/kohavy/Work/os/target/kernel.img' > ~/.bash_history
