FROM debian:jessie

RUN apt-get update -y

RUN apt-get install -y make
RUN apt-get install -y pkg-config 
RUN apt-get install -y gcc-arm-none-eabi 
RUN apt-get install -y gdb-arm-none-eabi 
RUN apt-get install -y git
